# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Prefecture.create([
  { id:1, name: "北海道", name_spoken: "ほっかいどう"},
  { id:2, name: "青森県", name_spoken: "あおもりけん"},
  { id:3, name: "岩手県", name_spoken: "いわてけん"},
  { id:4, name: "宮城県", name_spoken: "みやぎけん"},
  { id:5, name: "秋田県", name_spoken: "あきたけん"},
  { id:6, name: "山形県", name_spoken: "やまがたけん"},
  { id:7, name: "福島県", name_spoken: "ふくしまけん"},
  { id:8, name: "茨城県", name_spoken: "いばらきけん"},
  { id:9, name: "栃木県", name_spoken: "とちぎけん"},
  { id:10, name: "群馬県", name_spoken: "ぐんまけん"},
  { id:11, name: "埼玉県", name_spoken: "さいたまけん"},
  { id:12, name: "千葉県", name_spoken: "ちばけん"},
  { id:13, name: "東京都", name_spoken: "とうきょうと"},
  { id:14, name: "神奈川県", name_spoken: "かながわけん"},
  { id:15, name: "新潟県", name_spoken: "にいがたけん"},
  { id:16, name: "富山県", name_spoken: "とやまけん"},
  { id:17, name: "石川県", name_spoken: "いしかわけん"},
  { id:18, name: "福井県", name_spoken: "ふくいけん"},
  { id:19, name: "山梨県", name_spoken: "やまなしけん"},
  { id:20, name: "長野県", name_spoken: "ながのけん"},
  { id:21, name: "岐阜県", name_spoken: "ぎふけん"},
  { id:22, name: "静岡県", name_spoken: "しずおかけん"},
  { id:23, name: "愛知県", name_spoken: "あいちけん"},
  { id:24, name: "三重県", name_spoken: "みえけん"},
  { id:25, name: "滋賀県", name_spoken: "しがけん"},
  { id:26, name: "京都府", name_spoken: "きょうとふ"},
  { id:27, name: "大阪府", name_spoken: "おおさかふ"},
  { id:28, name: "兵庫県", name_spoken: "ひょうごけん"},
  { id:29, name: "奈良県", name_spoken: "ならけん"},
  { id:30, name: "和歌山県", name_spoken: "わかやまけん"},
  { id:31, name: "鳥取県", name_spoken: "とっとりけん"},
  { id:32, name: "島根県", name_spoken: "しまねけん"},
  { id:33, name: "岡山県", name_spoken: "おかやまけん"},
  { id:34, name: "広島県", name_spoken: "ひろしまけん"},
  { id:35, name: "山口県", name_spoken: "やまぐちけん"},
  { id:36, name: "徳島県", name_spoken: "とくしまけん"},
  { id:37, name: "香川県", name_spoken: "かがわけん"},
  { id:38, name: "愛媛県", name_spoken: "えひめけん"},
  { id:39, name: "高知県", name_spoken: "こうちけん"},
  { id:40, name: "福岡県", name_spoken: "ふくおかけん"},
  { id:41, name: "佐賀県", name_spoken: "さがけん"},
  { id:42, name: "長崎県", name_spoken: "ながさきけん"},
  { id:43, name: "熊本県", name_spoken: "くまもとけん"},
  { id:44, name: "大分県", name_spoken: "おおいたけん"},
  { id:45, name: "宮崎県", name_spoken: "みやざきけん"},
  { id:46, name: "鹿児島県", name_spoken: "かごしまけん"},
  { id:47, name: "沖縄県", name_spoken: "おきなわけん"}
])
