# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Prefecture.create([
  { id:1, name: "北海道", name_spoken: "ほっかいどう"},
  { id:2, name: "青森県", name_spoken: "あおもりけん"},
  { id:3, name: "岩手県", name_spoken: "いわてけん"},
  { id:4, name: "宮城県", name_spoken: "みやぎけん"},
  { id:5, name: "秋田県", name_spoken: "あきたけん"},
  { id:6, name: "山形県", name_spoken: "やまがたけん"},
  { id:7, name: "福島県", name_spoken: "ふくしまけん"},
  { id:8, name: "茨城県", name_spoken: "いばらきけん"},
  { id:9, name: "栃木県", name_spoken: "とちぎけん"},
  { id:10, name: "群馬県", name_spoken: "ぐんまけん"},
  { id:11, name: "埼玉県", name_spoken: "さいたまけん"},
  { id:12, name: "千葉県", name_spoken: "ちばけん"},
  { id:13, name: "東京都", name_spoken: "とうきょうと"},
  { id:14, name: "神奈川県", name_spoken: "かながわけん"},
  { id:15, name: "新潟県", name_spoken: "にいがたけん"},
  { id:16, name: "富山県", name_spoken: "とやまけん"},
  { id:17, name: "石川県", name_spoken: "いしかわけん"},
  { id:18, name: "福井県", name_spoken: "ふくいけん"},
  { id:19, name: "山梨県", name_spoken: "やまなしけん"},
  { id:20, name: "長野県", name_spoken: "ながのけん"},
  { id:21, name: "岐阜県", name_spoken: "ぎふけん"},
  { id:22, name: "静岡県", name_spoken: "しずおかけん"},
  { id:23, name: "愛知県", name_spoken: "あいちけん"},
  { id:24, name: "三重県", name_spoken: "みえけん"},
  { id:25, name: "滋賀県", name_spoken: "しがけん"},
  { id:26, name: "京都府", name_spoken: "きょうとふ"},
  { id:27, name: "大阪府", name_spoken: "おおさかふ"},
  { id:28, name: "兵庫県", name_spoken: "ひょうごけん"},
  { id:29, name: "奈良県", name_spoken: "ならけん"},
  { id:30, name: "和歌山県", name_spoken: "わかやまけん"},
  { id:31, name: "鳥取県", name_spoken: "とっとりけん"},
  { id:32, name: "島根県", name_spoken: "しまねけん"},
  { id:33, name: "岡山県", name_spoken: "おかやまけん"},
  { id:34, name: "広島県", name_spoken: "ひろしまけん"},
  { id:35, name: "山口県", name_spoken: "やまぐちけん"},
  { id:36, name: "徳島県", name_spoken: "とくしまけん"},
  { id:37, name: "香川県", name_spoken: "かがわけん"},
  { id:38, name: "愛媛県", name_spoken: "えひめけん"},
  { id:39, name: "高知県", name_spoken: "こうちけん"},
  { id:40, name: "福岡県", name_spoken: "ふくおかけん"},
  { id:41, name: "佐賀県", name_spoken: "さがけん"},
  { id:42, name: "長崎県", name_spoken: "ながさきけん"},
  { id:43, name: "熊本県", name_spoken: "くまもとけん"},
  { id:44, name: "大分県", name_spoken: "おおいたけん"},
  { id:45, name: "宮崎県", name_spoken: "みやざきけん"},
  { id:46, name: "鹿児島県", name_spoken: "かごしまけん"},
  { id:47, name: "沖縄県", name_spoken: "おきなわけん"}
])

Genre.create([
  # ジャンルL
  {id: 1, name: "見る", parent_id: nil, level:1},
  {id: 2, name: "イベント", parent_id: nil, level:1},
  {id: 3, name: "遊ぶ", parent_id: nil, level:1},
  {id: 4, name: "買う", parent_id: nil, level:1},
  {id: 5, name: "食べる", parent_id: nil, level:1},
  {id: 6, name: "乗り物", parent_id: nil, level:1},
  {id: 7, name: "泊まる", parent_id: nil, level:1},
  {id: 8, name: "その他", parent_id: nil, level:1},
  # ジャンルM
  {id: 9, name: "自然景観", parent_id: 1, level:2},
  {id: 10, name: "施設景観", parent_id: 1, level:2},
  {id: 11, name: "公園・庭園", parent_id: 1, level:2},
  {id: 12, name: "動・植物", parent_id: 1, level:2},
  {id: 13, name: "文化史跡", parent_id: 1, level:2},
  {id: 14, name: "文化施設", parent_id: 1, level:2},
  {id: 15, name: "神社仏閣", parent_id: 1, level:2},
  {id: 16, name: "地域風俗・風習", parent_id: 1, level:2},
  {id: 17, name: "その他", parent_id: 1, level:2},
  {id: 18, name: "祭事", parent_id: 2, level:2},
  {id: 19, name: "イベント", parent_id: 2, level:2},
  {id: 20, name: "イベント鑑賞", parent_id: 2, level:2},
  {id: 21, name: "その他", parent_id: 2, level:2},
  {id: 22, name: "文化施設", parent_id: 3, level:2},
  {id: 23, name: "スポーツ・レジャー", parent_id: 3, level:2},
  {id: 24, name: "温泉", parent_id: 3, level:2},
  {id: 25, name: "その他", parent_id: 3, level:2},
  {id: 26, name: "名産品", parent_id: 4, level:2},
  {id: 27, name: "その他", parent_id: 4, level:2},
  {id: 28, name: "郷土料理店", parent_id: 5, level:2},
  {id: 29, name: "その他", parent_id: 5, level:2},
  {id: 30, name: "車", parent_id: 6, level:2},
  {id: 31, name: "その他乗り物", parent_id: 6, level:2},
  {id: 32, name: "旅館", parent_id: 7, level:2},
  {id: 33, name: "ホテル", parent_id: 7, level:2},
  {id: 34, name: "民宿・ペンション", parent_id: 7, level:2},
  {id: 35, name: "その他", parent_id: 7, level:2},
  {id: 36, name: "その他", parent_id: 8, level:2},
  # ジャンルS
  {id: 37, name: "山岳", parent_id: 9, level:3},
  {id: 38, name: "高原", parent_id: 9, level:3},
  {id: 39, name: "湖沼", parent_id: 9, level:3},
  {id: 40, name: "河川景観", parent_id: 9, level:3},
  {id: 41, name: "海岸景観", parent_id: 9, level:3},
  {id: 42, name: "海中公園", parent_id: 9, level:3},
  {id: 43, name: "その他(特殊地形),", parent_id: 9, level:3},
  {id: 44, name: "自然現象", parent_id: 9, level:3},
  {id: 45, name: "町並み", parent_id: 10, level:3},
  {id: 46, name: "郷土景観", parent_id: 10, level:3},
  {id: 47, name: "展望施設", parent_id: 10, level:3},
  {id: 48, name: "公園", parent_id: 11, level:3},
  {id: 49, name: "庭園", parent_id: 11, level:3},
  {id: 50, name: "動物", parent_id: 12, level:3},
  {id: 51, name: "植物", parent_id: 12, level:3},
  {id: 52, name: "城郭", parent_id: 13, level:3},
  {id: 53, name: "旧街道", parent_id: 13, level:3},
  {id: 54, name: "史跡", parent_id: 13, level:3},
  {id: 55, name: "歴史的建造物", parent_id: 14, level:3},
  {id: 56, name: "近代的建造物", parent_id: 14, level:3},
  {id: 57, name: "博物館", parent_id: 14, level:3},
  {id: 58, name: "美術館", parent_id: 14, level:3},
  {id: 59, name: "動・植物園", parent_id: 14, level:3},
  {id: 60, name: "水族館", parent_id: 14, level:3},
  {id: 61, name: "産業観光施設", parent_id: 14, level:3},
  {id: 62, name: "道の駅(見る),", parent_id: 14, level:3},
  {id: 63, name: "神社・仏閣等", parent_id: 15, level:3},
  {id: 64, name: "地域風俗", parent_id: 16, level:3},
  {id: 65, name: "アニメ・音楽舞台", parent_id: 17, level:3},
  {id: 66, name: "映画・ドラマロケ地", parent_id: 17, level:3},
  {id: 67, name: "その他(名所),", parent_id: 17, level:3},
  {id: 68, name: "行事・祭事", parent_id: 18, level:3},
  {id: 69, name: "花見", parent_id: 19, level:3},
  {id: 70, name: "花火大会", parent_id: 19, level:3},
  {id: 71, name: "郷土芸能", parent_id: 20, level:3},
  {id: 72, name: "その他(イべント),", parent_id: 21, level:3},
  {id: 73, name: "センター施設", parent_id: 22, level:3},
  {id: 74, name: "道の駅(遊ぶ),", parent_id: 22, level:3},
  {id: 75, name: "スポーツ・リゾート施設", parent_id: 23, level:3},
  {id: 76, name: "サイクリングセンター", parent_id: 23, level:3},
  {id: 77, name: "センター施設", parent_id: 23, level:3},
  {id: 78, name: "キャンプ場", parent_id: 23, level:3},
  {id: 79, name: "フィールド・アスレチック", parent_id: 23, level:3},
  {id: 80, name: "フィールド・アーチェリー場", parent_id: 23, level:3},
  {id: 81, name: "スケート場", parent_id: 23, level:3},
  {id: 82, name: "スキー場", parent_id: 23, level:3},
  {id: 83, name: "マリーナ・ヨットハーバー", parent_id: 23, level:3},
  {id: 84, name: "サイクリングコース", parent_id: 23, level:3},
  {id: 85, name: "ハイキングコース", parent_id: 23, level:3},
  {id: 86, name: "自然歩道・自然研究路", parent_id: 23, level:3},
  {id: 87, name: "オリエンテーリング・パーマネントコース", parent_id: 23, level:3},
  {id: 88, name: "海水浴場", parent_id: 23, level:3},
  {id: 89, name: "観光農林業(体験含む),", parent_id: 23, level:3},
  {id: 90, name: "観光牧場(体験含む),", parent_id: 23, level:3},
  {id: 91, name: "観光漁業(体験含む),", parent_id: 23, level:3},
  {id: 92, name: "テーマパーク・レジャーランド", parent_id: 23, level:3},
  {id: 93, name: "温泉", parent_id: 24, level:3},
  {id: 94, name: "その他(遊ぶ),", parent_id: 25, level:3},
  {id: 95, name: "ショッピング店", parent_id: 26, level:3},
  {id: 96, name: "伝統工芸技術", parent_id: 26, level:3},
  {id: 97, name: "その他(買う),", parent_id: 27, level:3},
  {id: 98, name: "郷土料理店", parent_id: 28, level:3},
  {id: 99, name: "その他(食べる),", parent_id: 29, level:3},
  {id: 100, name: "観光タクシー・ハイヤー・レンタカー", parent_id: 30, level:3},
  {id: 101, name: "ケーブルカー・ロープウェイ", parent_id: 31, level:3},
  {id: 102, name: "レンタサイクル", parent_id: 31, level:3},
  {id: 103, name: "遊覧船", parent_id: 31, level:3},
  {id: 104, name: "遊覧飛行機", parent_id: 31, level:3},
  {id: 105, name: "観光列車", parent_id: 31, level:3},
  {id: 106, name: "観光周遊バス", parent_id: 31, level:3},
  {id: 107, name: "その他(乗り物),", parent_id: 31, level:3},
  {id: 108, name: "旅館", parent_id: 32, level:3},
  {id: 109, name: "シティホテル", parent_id: 33, level:3},
  {id: 110, name: "ビジネスホテル", parent_id: 33, level:3},
  {id: 111, name: "リゾートホテル", parent_id: 33, level:3},
  {id: 112, name: "その他(ホテル),", parent_id: 33, level:3},
  {id: 113, name: "民宿", parent_id: 34, level:3},
  {id: 114, name: "ペンション", parent_id: 34, level:3},
  {id: 115, name: "その他(泊まる),", parent_id: 35, level:3},
  {id: 116, name: "その他(その他),", parent_id: 36, level:3},
  ])
